---
  - name: Static Web
    hosts: localhost
    gather_facts: no
    tasks:
  
      - name: Create ConfigMap for website content
        k8s:
          state: present
          definition:
            apiVersion: v1
            kind: ConfigMap
            metadata:
              name: website-content-config
            data:
              index.html: |
                <!DOCTYPE html>
                <html>
                <head>
                  <title>My Static Website</title>
                </head>
                <body>
                  <h1>Welcome to My Static Website!</h1>
                  <p>This website is served by Nginx running on Kubernetes.</p>
                </body>
                </html>
  
      - name: Deploy Static Web
        k8s:
          state: present
          definition:
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: static-website-deployment
              labels:
                app: static-website
            spec:
              replicas: 3
              selector:
                matchLabels:
                  app: static-website
              template:
                metadata:
                  labels:
                    app: static-website
                spec:
                  containers:
                  - name: nginx
                    image: nginx:alpine
                    ports:
                    - containerPort: 80
                    volumeMounts:
                    - name: website-content
                      mountPath: /usr/share/nginx/html
                  volumes:
                  - name: website-content
                    configMap:
                      name: website-content-config
  
      - name: Create svc expose
        k8s:
          state: present
          definition:
            apiVersion: v1
            kind: Service
            metadata:
              name: static-website-service
            spec:
              selector:
                app: static-website
              ports:
              - protocol: TCP
                port: 80
                targetPort: 80
              type: NodePort  # Change to LoadBalancer or ClusterIP as needed
  