name: Terraform CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform CI
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Terraform CLI
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6 # Specify your Terraform version

      # Step 3: Change to the Project1 directory
      - name: Change to Project1 directory
        working-directory: ./Project 1
        run: pwd

      # Step 4: Terraform Init & format
      - name: Initialize Terraform
        working-directory: ./Project 1
        run: terraform init

      - name: Initialize Terraform
        working-directory: ./Project 1
        run: terraform fmt -recursive

      # Step 5: Terraform Validate
      - name: Validate Terraform configuration
        working-directory: ./Project 1
        run: terraform validate

      # Step 6: Terraform Plan with tfvars file
      - name: Generate Terraform Plan
        working-directory: ./Project 1
        run: terraform plan -var-file="terraform.tfvars" -out=tfplan

      # Step 7: Save Terraform Plan (Optional)
      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: ./Project 1/tfplan

      # Step 8: Terraform Apply (Optional for Manual Approval)
      - name: Apply Terraform Plan
        if: github.event_name == 'workflow_dispatch' # Only runs on manual trigger
        working-directory: ./Project 1
        run: terraform apply -var-file="terraform.tfvars" -auto-approve
