name: Secure Terraform CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  checkov:
    name: Checkov Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkov Scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: Project 1
          framework: terraform  
          download_external_modules: true 
          soft_fail: false 
         

  terraform:
    name: Terraform Deployment
    runs-on: ubuntu-latest
    
    # 1) Reference your environment here. Replace 'AzureP1' with your actual environment name if different.
    environment: AzureP1

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Terraform CLI
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6  # Use your preferred version

      # Step 3: Terraform Init (Uses environment variables for Azure auth)
      - name: Terraform Init
        working-directory: Project 1
        run: terraform init

      # Step 4: Terraform Validate
      - name: Validate Terraform configuration
        working-directory: Project 1
        run: terraform validate

      # Step 5: Terraform Plan
      - name: Generate Terraform Plan
        working-directory: Project 1
        run: terraform plan -var="client_id=${{ secrets.ARM_CLIENT_ID }}" -var="client_secret=${{ secrets.ARM_CLIENT_SECRET }}" 
            -var="tenant_id=${{ secrets.ARM_TENANT_ID }}" -var="subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}" -var="admin_username=${{ secrets.ARM_ADMIN_USERNAME }}" 
            -var="admin_password=${{ secrets.ARM_ADMIN_PASSWORD }}" -var="resource_group_name= ${{ secrets.ARM_RESOURCE_GROUP_NAME }}" -var="resource_location=${{ secrets.ARM_RESOURCE_LOCATION }}" # ... Add all vars here
        env:  # Pass credentials via env (safer than tfvars)
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_ADMIN_USERNAME: ${{ secrets.ARM_ADMIN_USERNAME }}
          ARM_ADMIN_PASSWORD: ${{ secrets.ARM_ADMIN_PASSWORD }}
          ARM_RESOURCE_GROUP_NAME: ${{ secrets.ARM_RESOURCE_GROUP_NAME }}
          ARM_RESOURCE_LOCATION: ${{ secrets.ARM_RESOURCE_LOCATION }}
