name: Terraform CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform CI
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Terraform CLI
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6 # Specify the desired Terraform version

      # Step 3: Terraform Init
      - name: Initialize Terraform
        run: terraform init

      # Step 4: Terraform Validate
      - name: Validate Terraform configuration
        run: terraform validate

      # Step 5: Terraform Plan
      - name: Generate Terraform Plan
        run: terraform plan -out=tfplan

      # Step 6: Save Terraform Plan (Optional)
      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve