name: Secure Terraform CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Deployment
    runs-on: ubuntu-latest
    
    # 1) Reference your environment here. Replace 'AzureP1' with your actual environment name if different.
    environment: AzureP1

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Terraform CLI
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6  # Use your preferred version

      # Step 3: Dynamically Create terraform.tfvars from Environment Secrets
      - name: Create terraform.tfvars
        working-directory: Project 1
        run: |
          echo "client_id       = \"${{ secrets.ARM_CLIENT_ID }}\"" > terraform.tfvars
          echo "client_secret   = \"${{ secrets.ARM_CLIENT_SECRET }}\"" >> terraform.tfvars
          echo "tenant_id       = \"${{ secrets.ARM_TENANT_ID }}\"" >> terraform.tfvars
          echo "subscription_id = \"${{ secrets.ARM_SUBSCRIPTION_ID }}\"" >> terraform.tfvars
          echo "admin_username  = \"${{ secrets.ADMIN_USERNAME }}\"" >> terraform.tfvars
          echo "admin_password  = \"${{ secrets.ADMIN_PASSWORD }}\"" >> terraform.tfvars
          echo "resource_group_name = \"${{ secrets.RESOURCE_GROUP_NAME }}\"" >> terraform.tfvars
          echo "resource_location   = \"${{ secrets.RESOURCE_LOCATION }}\"" >> terraform.tfvars

      # Step 4: Terraform Init (Uses environment variables for Azure auth)
      - name: Terraform Init
        working-directory: Project 1
        run: terraform init

      # Step 5: Terraform Validate
      - name: Validate Terraform configuration
        working-directory: Project 1
        run: terraform validate

      # Step 6: Terraform Plan
      - name: Generate Terraform Plan
        working-directory: Project 1
        run: terraform plan -var-file=terraform.tfvars -out=tfplan

      # Step 7: (Optional) Upload Terraform Plan
      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: Project 1/tfplan
